name: ci

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      -
        name: Build and push sd
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./client/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: philipslabs/cf-redis-exporter
          cache-from: type=registry,ref=philipslabs/cf-redis-exporter:latest
          cache-to: type=inline